version: 2
jobs:
  build:
    docker:
      - image: ishiko/gcc-ishiko-cpp-build-prerequisites:0.2.0
    steps:
      - run: 
          name: "Set ISHIKO_CPP environment variable and create workspace directory"
          command: mkdir -p /projects/ishiko/cpp && echo 'export ISHIKO_CPP="/projects/ishiko/cpp"' >> $BASH_ENV
      - run:
          name: "Install build dependency: Ishiko/C++ BasePlatform"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/base-platform.git && cd base-platform/build/gnumake && make
      - run:
          name: "Install build dependency: Ishiko/C++ Errors"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/errors.git && cd errors/build/gnumake && make
      - run:
          name: "Install build dependency: Ishiko/C++ Types"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/types.git && cd types/build/gnumake && make
      - run:
          name: "Install build dependency: Ishiko/C++ Collections"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/collections.git && cd collections/build/gnumake && make
      - run:
          name: "Install build dependency: Ishiko/C++ Text"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/text.git && cd text/build/gnumake && make
      - run:
          name: "Install build dependency: Ishiko/C++ Process"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/process.git && cd process/build/gnumake && make
      - run:
          name: "Install build dependency: Ishiko/C++ FileSystem"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/filesystem.git && cd filesystem/build/gnumake && make
      - run:
          name: "Install build dependency: Ishiko/C++ Diff"
          command: cd /projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/diff.git && cd diff/build/gnumake && make
      - checkout:
          path: /projects/ishiko/cpp/test-framework
      - run:
          name: "Build TestFramework/Core"
          command: cd /projects/ishiko/cpp/test-framework/core/build/gnumake && make
      - run:
          name: Test build
          command: cd /projects/ishiko/cpp/test-framework/core/tests/build/gnumake && make
      - run:
          name: Build ExitCodeTestHelper
          command: cd /projects/ishiko/cpp/test-framework/core/tests/exitcodetesthelper/build/gnumake && make
      - run:
          name: Build PermanentAppTestHelper
          command: cd /projects/ishiko/cpp/test-framework/core/tests/permanentapptesthelper/build/gnumake && make
      - run:
          name: Build StandardOutputTestHelper
          command: cd /projects/ishiko/cpp/test-framework/core/tests/standardoutputtesthelper/build/gnumake && make
      - run:
          name: Build WriteFileTestHelper
          command: cd /projects/ishiko/cpp/test-framework/core/tests/writefiletesthelper/build/gnumake && make
      - run:
          name: Run the tests
          command: cd /projects/ishiko/cpp/test-framework/core/tests/build/gnumake && ./IshikoTestFrameworkCoreTests
      - store_test_results:
          path: /projects/ishiko/cpp/test-framework/output/sub/junit.xml
      - run:
          name: "Build Tests"
          command: cd /projects/ishiko/cpp/test-framework/build/gnumake && make
workflows:
  version: 2
  continuous_build:
    jobs:
      - build
  weekly_build:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
