// SPDX-FileCopyrightText: 2000-2024 Xavier Leclercq
// SPDX-License-Identifier: BSL-1.0

#ifndef GUARD_ISHIKO_CPP_TESTFRAMEWORK_CORE_ACTIONS_COPYFILESACTION_HPP
#define GUARD_ISHIKO_CPP_TESTFRAMEWORK_CORE_ACTIONS_COPYFILESACTION_HPP

#endif
